version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 23-x64

build: off

build_script:
  - cd C:\projects\oj\ext\oj
  - ruby extconf.rb
  - make

before_test:
  - ruby -v
  - gem -v
  - bundle -v
