version: 1.0.{build}-{branch}

image: Visual Studio 2015

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: dNPsSiN7aAwAe2K7Aw+IVw==
  RUBY_VERSION: 23-x64
 # PATH: C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH%
  
 
build: off

before_build:
  - SET PATH=c:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH%
  - ruby -v
  - make -v
  - ps: $env:path -split ";"

build_script:
  - cd C:\projects\oj\ext\oj
  - ruby extconf.rb
  - make

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
