version: 1.0.{build}-{branch}

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image: Visual Studio 2015

environment:
  APPVEYOR_RDP_PASSWORD: fixm3-wtf
  RUBY_VERSION: 23-x64
  PATH: C:\Ruby%RUBY_VERSION%\bin;C:\Ruby23-x64\DevKit\bin;%PATH%

#  matrix:
#    - RUBY_VERSION: 23-x64
 
build: off

before_build:
  - ruby -v
  - make -v

#- set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Ruby23-x64\DevKit\bin;%PATH%

# make does not exits, hmm
build_script:
  - cd C:\projects\oj\ext\oj
  - ruby extconf.rb
  - make

